### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by korewatori** [tarunm20/4anime-scraper#9]
When installing using NPM and using it straight away, there's a TypeError stating that it "cannot read property 'replace' of undefined".

Really simple code I just slapped into a .JS file:
```
const Anime = require('4anime-scraper').default;

Anime.getAnimeFromURL("https://4anime.to/anime/bleach").then(res => {
	console.log(res);
});
```

The console already outputs:
```
[
  [ '' ],
  [ 'Bookmark' ],
  [ 'Change color of watched' ],
  [ ' Type TV Series' ],
  [ 'Studio Studio Pierrot' ],
  'Release Date (JP) Fall, 2004',
  'Status Completed',
  'Language Subbed  '
]
```
...but the first field is blank, should that be the name?

The error is in `index.js` at line 71:45.

**Comment by tarunm20** [comment]
Hey, thanks for sending in the issue, I'll check it out.

**Comment by tarunm20** [comment]
Okay, I figured out the problem. The HTML layout has changed so the HTML parser I'm using isn't picking up the right info. I'm working on a fix right now.

**Comment by tarunm20** [comment]
I've published a fix to NPM and I've updated the git repo. Could you try it as well just to see if it works?

**Comment by korewatori** [comment]
That seems to have helped. Thank you.
Though if I may ask, is there any chance you could send me an example script to work with this? I'm a bit too busy to write one myself but I would really like to use it. I understand if not though.

Thanks again

**Comment by tarunm20** [comment]
What do you mean by example script? Like how to use the package?

**Comment by korewatori** [comment]
Kind of. Something sort-of basic that would just show people how to use it yeah

**Comment by tarunm20** [comment]
In terms of documentation, I've written about it in the README.md but if you're asking for a specific use case for the package I haven't gotten around to developing one yet.
